  - name: "technology"
    identifier_field: name
    label: "Technology"
    folder: "content/technologies"
    preview_path: "technologies/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
    - { label: "Name", name: "name", widget: "string" }
    - { label: "Description", name: "description", widget: "string", required: false }
    - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        required: false,
        media_library: { config: { multiple: false } },
      }